{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "spline2segmentedWalls_p",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [
    {
      "Id": "fbd0e50f8f184f3cbbc7705bc08ed4d6",
      "Name": "Návod",
      "Type": "string",
      "Value": "vytvorí nasegmentované steny alebo Curtain Walls podľa krivky s voliteľnou dĺžkou segmentu",
      "Description": "Creates a string."
    },
    {
      "Id": "4ec9239b2d034fbf9b8dcedbdd1f5cfe",
      "Name": "segment length",
      "Type": "number",
      "Value": "900",
      "MaximumValue": 8000.0,
      "MinimumValue": 200.0,
      "StepValue": 50.0,
      "NumberType": "Double",
      "Description": "A slider that produces numeric values."
    }
  ],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.CurveElement.Curve",
      "Id": "2a08aa9697b2470398d1d7f8d0b399b7",
      "Inputs": [
        {
          "Id": "3e5b365d7b5a4f398fff31549a86a3c8",
          "Name": "curveElement",
          "Description": "Revit.Elements.CurveElement",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3801f4742c5e4c53abe08512b34b4a95",
          "Name": "Curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Obtain the geometry curve for this geometry curve\n\nCurveElement.Curve: Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointsAtChordLengthFromPoint@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "18f9b12c33284b1abc93281d860770b5",
      "Inputs": [
        {
          "Id": "53fd3a7c10604e839a07f6c688547bc0",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9156f9d749984c44a5eed4673a64d2e7",
          "Name": "point",
          "Description": "The reference point from where to measure\n\nPoint\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1d1513c3dfbc44cc87a1c0331c759374",
          "Name": "chordLength",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0d0caa9ecfba4177b75dc29adc2e0015",
          "Name": "Point[]",
          "Description": "List of points on curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns points spaced on the curve at given chord length starting from the given point\n\nCurve.PointsAtChordLengthFromPoint (point: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), chordLength: double = 1): Point[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.SplitByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "709b6ccf2e3d4e52b9b4f131631ffe9f",
      "Inputs": [
        {
          "Id": "8f4df4c9a3ef44bb9384240155bf0769",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "91ce08c6a1f54ec192ed94dae1f4e641",
          "Name": "points",
          "Description": "The points on the curve at which to split the curve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b9e13305e179471f96144e5401cd38cf",
          "Name": "Curve[]",
          "Description": "Curves created from splitting",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Split a Curve into multiple pieces at the given points\n\nCurve.SplitByPoints (points: Point[]): Curve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.EndPoint",
      "Id": "b2ac5345d5654f3895919e509ba72737",
      "Inputs": [
        {
          "Id": "509788ed876b41c4b82fbf4f96423ee4",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "91a5b930f76f4e5d8b93717a7abe8816",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the end Point along the Curve\n\nCurve.EndPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
      "Id": "2c022dd2f0a947a8a87175388ff4c66d",
      "Inputs": [
        {
          "Id": "6a788116d9cd409a9bbacf6a1bd221cf",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5de8e6b1c6714279aaf010a7116eeb4c",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the start Point along the Curve\n\nCurve.StartPoint: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "2fc262c58c664aeab4049805f3a55bbd",
      "Inputs": [
        {
          "Id": "7e7de5531b9a4085ae61bd90f0a3b3e8",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "61d81c42a7b34290bc4348d604cd3200",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "362470a181ec4559b2d269cc2d85c029",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.StringInput, CoreNodeModels",
      "NodeType": "StringInputNode",
      "InputValue": "vytvorí nasegmentované steny alebo Curtain Walls podľa krivky s voliteľnou dĺžkou segmentu",
      "Id": "fbd0e50f8f184f3cbbc7705bc08ed4d6",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "1e81fa0dac0140dbad18f4032c73f7a1",
          "Name": "",
          "Description": "String",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a string."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "721bccf9f1ab477daf7900e268f1f64d",
      "Inputs": [
        {
          "Id": "cee4bb06a3bc43ee97baf9c8549c5c38",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d73b2e5c05874290a3c0ff3434010983",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    },
    {
      "ConcreteType": "Dynamo.Nodes.DSModelElementSelection, DSRevitNodesUI",
      "NodeType": "ExtensionNode",
      "InstanceId": [
        "693c88f8-b0c1-45f1-9e61-0105a6796f0b-00244a95"
      ],
      "Id": "c1b9d2efed634de29ad2f3ea11195c25",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "26a6ecf69fc74de9acc79fb4edd43126",
          "Name": "Element",
          "Description": "The selected elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleSlider, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "MaximumValue": 8000.0,
      "MinimumValue": 200.0,
      "StepValue": 50.0,
      "InputValue": 900.0,
      "Id": "4ec9239b2d034fbf9b8dcedbdd1f5cfe",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7b55f36a425f49499aecd14d0fc9bf75",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A slider that produces numeric values."
    },
    {
      "ConcreteType": "DSRevitNodesUI.WallTypes, DSRevitNodesUI",
      "SelectedIndex": -1,
      "SelectedString": "oporne mury 300mm",
      "NodeType": "ExtensionNode",
      "Id": "9c3fda602cf2482a8b8640a3dcd47758",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2140b23a805346bc8d0d24e95b2db82c",
          "Name": "Wall Type",
          "Description": "The selected Wall Type",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "All wall types available in the document."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Wall.ByCurveAndLevels@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Revit.Elements.Level,Revit.Elements.WallType",
      "Id": "e4752e3e126d48398c75f047c5bb11bc",
      "Inputs": [
        {
          "Id": "606f59d9677343dbac4c1a96424c4e58",
          "Name": "c",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a129d510f77249c1b58592f5577d5c92",
          "Name": "startLevel",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "070a5113454849fba619aeb9d30f677c",
          "Name": "endLevel",
          "Description": "Level",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ba4e2a401d5b4e6aaab096d7a32bdd3f",
          "Name": "wallType",
          "Description": "WallType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ed3ead1a67c149c8a0aebdf24c93c405",
          "Name": "Wall",
          "Description": "Wall",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Revit Wall from a guiding Curve, start Level, end Level, and WallType\n\nWall.ByCurveAndLevels (c: Curve, startLevel: Level, endLevel: Level, wallType: WallType): Wall"
    },
    {
      "ConcreteType": "DSRevitNodesUI.Levels, DSRevitNodesUI",
      "SelectedIndex": 0,
      "SelectedString": "lamely pata",
      "NodeType": "ExtensionNode",
      "Id": "cd59eec027814ccd8beac06fe6897f07",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7a8442481cec46ce89a73eef94c1da9b",
          "Name": "Levels",
          "Description": "The selected Levels",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Select a level in the active document"
    },
    {
      "ConcreteType": "DSRevitNodesUI.Levels, DSRevitNodesUI",
      "SelectedIndex": 0,
      "SelectedString": "Level 1",
      "NodeType": "ExtensionNode",
      "Id": "9fa599e6b4f84c6bb1436688d3bd5dcd",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "11ec645be2a3480e9d27db953340bcf2",
          "Name": "Levels",
          "Description": "The selected Levels",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Select a level in the active document"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\n\r\nfrom datetime import datetime\r\nimport getpass\r\n\r\n# name of the script for log\r\nlog_string = \"spline2segmentedWalls\"\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\nfilePath = doc.PathName\r\n\r\n# getting file name from path\r\nlastBackslash = filePath.rindex(\"\\\\\")+1\r\nfile_name = filePath[lastBackslash:]\r\nuser_name = getpass.getuser()\r\ndatestamp = str(datetime.now())\r\n# tabulator between data to easy import to excel schedule\r\nseparator = \"\\t\"\r\nline = datestamp + separator + log_string + separator + user_name + \"\\n\"\r\n\r\ntry:\r\n\tf = open(\"L:\\\\customToolslogs\\\\dynLogs\\\\\" + file_name +\".log\", \"a\")\r\n\tf.write(line)\r\n\tf.close()\r\n\tstatus = \"log has been written\"\r\nexcept:\r\n\tstatus = \"something went wrong\"\r\n\r\n# Assign your output to the OUT variable.\r\nOUT = status",
      "VariableInputPorts": true,
      "Id": "c014e98d9e0b45f4af68076b1dfb032e",
      "Inputs": [
        {
          "Id": "728caef3b0374f8ab135c4b3b3736c72",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8aaf87b1495b4242ad1a323d8e98901b",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [
    {
      "Start": "3801f4742c5e4c53abe08512b34b4a95",
      "End": "53fd3a7c10604e839a07f6c688547bc0",
      "Id": "e66f3600aaca4497b4724c2aebdf1c1b"
    },
    {
      "Start": "3801f4742c5e4c53abe08512b34b4a95",
      "End": "8f4df4c9a3ef44bb9384240155bf0769",
      "Id": "5c45f75b50864f8da4656099a7643ed1"
    },
    {
      "Start": "0d0caa9ecfba4177b75dc29adc2e0015",
      "End": "91ce08c6a1f54ec192ed94dae1f4e641",
      "Id": "8da75e9700854a8da032cae1b54e76dd"
    },
    {
      "Start": "b9e13305e179471f96144e5401cd38cf",
      "End": "6a788116d9cd409a9bbacf6a1bd221cf",
      "Id": "3a147118642c41088562c5bc45203354"
    },
    {
      "Start": "b9e13305e179471f96144e5401cd38cf",
      "End": "509788ed876b41c4b82fbf4f96423ee4",
      "Id": "3a0ca7b31b77497ab11a8f48c1fcfe01"
    },
    {
      "Start": "b9e13305e179471f96144e5401cd38cf",
      "End": "cee4bb06a3bc43ee97baf9c8549c5c38",
      "Id": "49fb5da50f994d989ca993b58c0aae44"
    },
    {
      "Start": "91a5b930f76f4e5d8b93717a7abe8816",
      "End": "61d81c42a7b34290bc4348d604cd3200",
      "Id": "032f3264dddf49a0bfdf5208f352c522"
    },
    {
      "Start": "5de8e6b1c6714279aaf010a7116eeb4c",
      "End": "7e7de5531b9a4085ae61bd90f0a3b3e8",
      "Id": "fb98de635e444087a3b0e0d44fddc3a4"
    },
    {
      "Start": "362470a181ec4559b2d269cc2d85c029",
      "End": "606f59d9677343dbac4c1a96424c4e58",
      "Id": "11e67c47bc8f4bafb46148879d7fe5bb"
    },
    {
      "Start": "26a6ecf69fc74de9acc79fb4edd43126",
      "End": "3e5b365d7b5a4f398fff31549a86a3c8",
      "Id": "7d1158bf919447459f67573957d07cad"
    },
    {
      "Start": "7b55f36a425f49499aecd14d0fc9bf75",
      "End": "1d1513c3dfbc44cc87a1c0331c759374",
      "Id": "645260cf2db94cc29f16fa0cfa23bb4d"
    },
    {
      "Start": "2140b23a805346bc8d0d24e95b2db82c",
      "End": "ba4e2a401d5b4e6aaab096d7a32bdd3f",
      "Id": "1a4920c86dcc40dea7b034be7ba880f5"
    },
    {
      "Start": "7a8442481cec46ce89a73eef94c1da9b",
      "End": "a129d510f77249c1b58592f5577d5c92",
      "Id": "a313b683968f40a3af82438efee5a57d"
    },
    {
      "Start": "11ec645be2a3480e9d27db953340bcf2",
      "End": "070a5113454849fba619aeb9d30f677c",
      "Id": "31a0944f8a5a4db3b3b864ddab11280e"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.3.0.5885",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": 476597.9375,
      "EyeY": 4343.21142578125,
      "EyeZ": -18396.50390625,
      "LookX": 2771.765869140625,
      "LookY": -3002.746337890625,
      "LookZ": -13396.8681640625,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "CurveElement.Curve",
        "Id": "2a08aa9697b2470398d1d7f8d0b399b7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 142.666095036314,
        "Y": -5.64400336147423
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PointsAtChordLengthFromPoint",
        "Id": "18f9b12c33284b1abc93281d860770b5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 401.780632565097,
        "Y": -240.380691206148
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.SplitByPoints",
        "Id": "709b6ccf2e3d4e52b9b4f131631ffe9f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 729.339574966201,
        "Y": -142.922454419913
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.EndPoint",
        "Id": "b2ac5345d5654f3895919e509ba72737",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 962.914544928641,
        "Y": -34.7781173133981
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.StartPoint",
        "Id": "2c022dd2f0a947a8a87175388ff4c66d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 962.914544928641,
        "Y": -170.435670356733
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "2fc262c58c664aeab4049805f3a55bbd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1246.45263462724,
        "Y": -28.4109727275285
      },
      {
        "ShowGeometry": true,
        "Name": "Návod",
        "Id": "fbd0e50f8f184f3cbbc7705bc08ed4d6",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -513.674458502494,
        "Y": -212.463515385883
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "721bccf9f1ab477daf7900e268f1f64d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 915.609282784415,
        "Y": 271.102497036518
      },
      {
        "ShowGeometry": true,
        "Name": "Select Model Line",
        "Id": "c1b9d2efed634de29ad2f3ea11195c25",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -204.175380840041,
        "Y": -70.9367589186924
      },
      {
        "ShowGeometry": true,
        "Name": "segment length",
        "Id": "4ec9239b2d034fbf9b8dcedbdd1f5cfe",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -248.152799557802,
        "Y": -151.233507827524
      },
      {
        "ShowGeometry": true,
        "Name": "Wall Types",
        "Id": "9c3fda602cf2482a8b8640a3dcd47758",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -231.89574021713793,
        "Y": 264.32628977716172
      },
      {
        "ShowGeometry": true,
        "Name": "Wall.ByCurveAndLevels",
        "Id": "e4752e3e126d48398c75f047c5bb11bc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1887.1161585797397,
        "Y": 154.37949576308998
      },
      {
        "ShowGeometry": true,
        "Name": "Levels start",
        "Id": "cd59eec027814ccd8beac06fe6897f07",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -216.23007063070793,
        "Y": 66.600275728945263
      },
      {
        "ShowGeometry": true,
        "Name": "Levels end",
        "Id": "9fa599e6b4f84c6bb1436688d3bd5dcd",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -224.10935056172866,
        "Y": 159.74703065780784
      },
      {
        "ShowGeometry": true,
        "Name": "PY log",
        "Id": "c014e98d9e0b45f4af68076b1dfb032e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -213.90625706294833,
        "Y": 386.01058699088043
      }
    ],
    "Annotations": [
      {
        "Id": "a71bca48b6564dc6b24c5bbe1af74109",
        "Title": "INPUT",
        "Nodes": [
          "c1b9d2efed634de29ad2f3ea11195c25",
          "4ec9239b2d034fbf9b8dcedbdd1f5cfe",
          "cd59eec027814ccd8beac06fe6897f07",
          "9fa599e6b4f84c6bb1436688d3bd5dcd",
          "9c3fda602cf2482a8b8640a3dcd47758"
        ],
        "Left": -258.15279955780204,
        "Top": -197.233507827524,
        "Width": 319.0,
        "Height": 554.55979760468574,
        "FontSize": 30.0,
        "InitialTop": -151.233507827524,
        "InitialHeight": 560.55979760468574,
        "TextblockHeight": 36.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 360.23832075481556,
    "Y": 22.203005857673418,
    "Zoom": 0.99270040032327667
  }
}