<Workspace Version="1.3.2.2480" X="-268.095328422004" Y="682.610677831047" zoom="0.59122681948266" ScaleFactor="10000" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="102d7f00-b6cd-4051-bafd-1861344d8735" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="CurveElement.Curve" x="1476.8189995916" y="-528.128638706908" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.CurveElement.Curve">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="3ff514e8-e135-4531-8c42-4501113ff62b" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Springs.Collector.ElementSketch" x="980.44126966773" y="-547.060586789195" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
      <ID value="94050ce4-e59f-4377-933d-16326991c630" />
      <Name value="Springs.Collector.ElementSketch" />
      <Description value="Get the actual sketch lines of a sketch based element (floor, ceiling, modified wall, etc.) . You can optionally fetch the matching model curves, however this might prove comptationally heavy on larger data sets." />
      <Inputs>
        <Input value="element" />
        <Input value="fetchModelCurves" />
        <Input value="refresh" />
      </Inputs>
      <Outputs>
        <Output value="curves" />
        <Output value="model curves" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <CoreNodeModels.Input.BoolSelector guid="58c22c32-99c1-4bbe-8cb4-82c514d7f262" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="797.008589294067" y="-394.84726083404" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0f602e5b-2f4e-48fd-835d-d850aff9b1a4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1399.00158087134" y="-378.334772537118" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0003b791-1e7b-43a5-8668-f5b9dad03fc5" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FilledRegion.ByCurves" x="1848.45175073091" y="-682.065313369511" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.FilledRegion.ByCurves@Revit.Elements.Views.View,Autodesk.DesignScript.Geometry.Curve[],Revit.Elements.FilledRegionType">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a33bbc53-ae74-4847-bfb0-f9eee6317b9f" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.Current" x="1295.27807791374" y="-806.506759691936" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.Current" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="42cb94ee-78a4-4a18-9fe7-a647dc4b7d80" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Document.ActiveView" x="1470.15437820193" y="-799.670384986847" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Application.Document.ActiveView">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.StringInput guid="95a7ae16-a497-486d-9069-1d85cb1a3bcd" type="CoreNodeModels.Input.StringInput" nickname="Návod" x="519.469193436599" y="-966.740484085611" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>Skopíruje Sketchlines zo sketch based elementov ako Floor, Subregion, Roof atd a nakresli podla nich Filled region v aktivnom View</System.String>
      <System.String value="Skopíruje Sketchlines zo sketch based elementov ako Floor, Subregion, Roof atd a nakresli podla nich Filled region v aktivnom View" />
    </CoreNodeModels.Input.StringInput>
    <Dynamo.Nodes.DSModelElementSelection guid="bb1343cb-2dc5-4230-ac9b-66385d78c86a" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select element" x="534.693821337794" y="-620.953337099638" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" />
    <DSRevitNodesUI.FilledRegionTypes guid="b1361422-0fba-4045-8072-51510fa0f230" type="DSRevitNodesUI.FilledRegionTypes" nickname="Select Filled Region Type" x="518.501538207713" y="-737.401466858152" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:Betón" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="102d7f00-b6cd-4051-bafd-1861344d8735" start_index="0" end="0003b791-1e7b-43a5-8668-f5b9dad03fc5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ff514e8-e135-4531-8c42-4501113ff62b" start_index="1" end="0f602e5b-2f4e-48fd-835d-d850aff9b1a4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ff514e8-e135-4531-8c42-4501113ff62b" start_index="1" end="102d7f00-b6cd-4051-bafd-1861344d8735" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="58c22c32-99c1-4bbe-8cb4-82c514d7f262" start_index="0" end="3ff514e8-e135-4531-8c42-4501113ff62b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a33bbc53-ae74-4847-bfb0-f9eee6317b9f" start_index="0" end="42cb94ee-78a4-4a18-9fe7-a647dc4b7d80" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="42cb94ee-78a4-4a18-9fe7-a647dc4b7d80" start_index="0" end="0003b791-1e7b-43a5-8668-f5b9dad03fc5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bb1343cb-2dc5-4230-ac9b-66385d78c86a" start_index="0" end="3ff514e8-e135-4531-8c42-4501113ff62b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b1361422-0fba-4045-8072-51510fa0f230" start_index="0" end="0003b791-1e7b-43a5-8668-f5b9dad03fc5" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="08b20f30-a0e7-4925-b5eb-4462690ab571" annotationText="INPUT" left="508.501538207713" top="-783.401466858152" width="234" height="281.448129758514" fontSize="30" InitialTop="-737.401466858152" InitialHeight="265.448129758514" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="bb1343cb-2dc5-4230-ac9b-66385d78c86a" />
      <Models ModelGuid="b1361422-0fba-4045-8072-51510fa0f230" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-4883.7802734375" eyeY="20868.955078125" eyeZ="92101.5234375" lookX="-18379.94921875" lookY="-37022.5" lookZ="-77688.265625" upX="-0.0498309582471848" upY="0.976296007633209" upZ="-0.210625216364861" />
  </Cameras>
</Workspace>